import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { SnackbarProvider } from "@/components/context/SnackbarContext";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // You can pick what you need
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Icon Shoppers",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <SnackbarProvider>
          {" "}
          {/* Wrap the app in SnackbarProvider */}
          {children}
        </SnackbarProvider>
        <Toaster 
          position="top-right"
          toastOptions={{
            classNames: {
              toast: "group toast group-[.toaster]:bg-red-500 group-[.toaster]:text-white group-[.toaster]:border-red-600 group-[.toaster]:shadow-lg",
              description: "group-[.toast]:text-red-100",
              actionButton: "group-[.toast]:bg-red-600 group-[.toast]:text-white",
              cancelButton: "group-[.toast]:bg-red-400 group-[.toast]:text-white",
            },
          }}
        />
      </body>
    </html>
  );
}