import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SnackbarProvider } from "@/components/context/SnackbarContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // You can pick what you need
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Icon Shoppers",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <SnackbarProvider>
          {" "}
          {/* Wrap the app in SnackbarProvider */}
          {children}
          <Toaster />
        </SnackbarProvider>
      </body>
    </html>
  );
}
